tuto_user:
    resource: "@TutoUserBundle/Resources/config/routing.yml"
    prefix:   /

redproject:
    resource: "@redprojectBundle/Resources/config/routing.yml"
    prefix:   /red

tuto_animaux:
    resource: "@TutoAnimauxBundle/Resources/config/routing.yml"
    prefix:   /

    # app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

