# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_USER, ROLE_MODERATEUR]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
    #authentification
        main:
        #peu importe le nom
            pattern: ^/
            form_login:
                provider: fos_userbundle 
                #fournisseur d'utilisateurs, ici il trouve ses membres dans FOS mais on aurait pu marquer in_memory
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true 
            # toujours a true sinon les anonymes ne passe pas la page d accueil
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path:   fos_user_security_logout
                target: /

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
    #autorisation
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_FULLY_AUTHENTICATED }
        - { path: ^/resetting, role: ROLE_USER }
        - { path: ^/admin/, role: ROLE_ADMIN }
