sdzblog_accueil:
    path: /{page}
    defaults: {_controller: blogBundle:Blog:index, page: 1}
    requirements: 
        page: \d*

sdzblog_voir:
    path: /article/{id}
    defaults: {_controller: blogBundle:Blog:voir}
    requirements:
        id: \d+

sdzblog_ajouter:
    path: /ajouter 
    defaults: {_controller: blogBundle:Blog:ajouter}

sdzblog_modifier:
    path: /modifier/{id}
    defaults: {_controller: blogBundle:Blog:modifier}
    requirements:
        id: \d+

sdzblog_supprimer:
    path: /supprimer/{id}
    defaults: {_controller: blogBundle:Blog:supprimer}
    requirements:
        id: \d+

